"""
prepare_data.py — convert geophone .mat recordings into data/walkers.js
for the footstep web page (index.html). Run locally or in Kaggle:

    python prepare_data.py

Edit the WALKERS list below to add/replace recordings. Labels are what the
audience sees — keep subject names out of them for a public page.
"""
import base64, json
import numpy as np
import scipy.io as sio
from scipy.signal import decimate, find_peaks, welch, iirnotch, filtfilt

FS_IN = 8000          # geophone sampling rate of the .mat files (Hz)
DECIM = 4             # 8000 -> 2000 Hz (99% of footstep energy is < 300 Hz)
MAX_SECONDS = 300     # trim long recordings to keep the page light
MAINS_HZ = 50         # notch out power-line hum + harmonics (India: 50 Hz); None to skip

WALKERS = [
    dict(file="Aayushi_wooden_3.mat",   id="A", label="Walker A",
         who="Female walker", floor="Wooden floor"),
    dict(file="AbhishekJTM_lhc_1.mat",  id="B", label="Walker B",
         who="Male walker",   floor="Lecture-hall floor"),
]

def process(w):
    x = sio.loadmat(w["file"])["geo_data"].ravel().astype(np.float64)
    x = x[: FS_IN * MAX_SECONDS]
    clip_frac = float(np.mean(np.abs(x) >= 0.999))
    x = x - np.mean(x)
    y = decimate(x, DECIM, ftype="fir", zero_phase=True)
    fs = FS_IN // DECIM
    if MAINS_HZ:
        for h in range(MAINS_HZ, fs // 2, MAINS_HZ):
            b, a = iirnotch(h, Q=30, fs=fs)
            y = filtfilt(b, a, y)

    # footstep detection: 30 ms RMS envelope, robust threshold, >=0.3 s apart
    win = int(0.03 * fs)
    env = np.sqrt(np.convolve(y * y, np.ones(win) / win, mode="same"))
    med = np.median(env); mad = np.median(np.abs(env - med)) + 1e-12
    peaks, _ = find_peaks(env, height=med + 8 * mad, distance=int(0.3 * fs))
    isi = np.diff(peaks) / fs
    walking_isi = isi[(isi > 0.3) & (isi < 1.2)]
    cadence = 60.0 / float(np.median(walking_isi)) if len(walking_isi) else 0.0

    f, p = welch(y, fs=fs, nperseg=4096)
    band = (f > 5) & (f < 500)
    dom_f = float(f[band][np.argmax(p[band])])

    scale = float(np.max(np.abs(y))) or 1.0
    q = np.clip(np.round(y / scale * 32767), -32768, 32767).astype("<i2")
    return dict(
        id=w["id"], label=w["label"], who=w["who"], floor=w["floor"],
        fs=fs, scale=scale, n=int(len(q)),
        steps=[int(i) for i in peaks],
        cadence=round(cadence, 1), dominantHz=round(dom_f, 1),
        clipFraction=clip_frac,
        b64=base64.b64encode(q.tobytes()).decode("ascii"),
    )

if __name__ == "__main__":
    out = [process(w) for w in WALKERS]
    with open("data/walkers.js", "w") as fh:
        fh.write("// generated by prepare_data.py\nwindow.WALKERS = ")
        json.dump(out, fh)
        fh.write(";\n")
    for o in out:
        print(f'{o["label"]}: {len(o["steps"])} steps, {o["cadence"]} steps/min, '
              f'peak {o["dominantHz"]} Hz, clipped {o["clipFraction"]*100:.2f}%')
